name = "DynamicStructs"
uuid = "e139c391-eeee-4818-b359-c8725224fb1f"
authors = ["anton083 <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
